apiVersion: v1
kind: Service
metadata:  
  name: connect-mongo
spec:
  selector:    
    app: auth-mongo
  type: LoadBalancer
  ports:  
  - name: http
    port: 27017
    targetPort: 27017
    protocol: TCP